// Run against the Vite dev server with Playwright available in NODE_PATH.
// All market responses are intercepted; no live provider is contacted.
const { chromium } = require('playwright')
const assert = require('node:assert/strict')

async function main() {
  const browser = await chromium.launch({ headless: true, channel: process.env.BACKTEST_BROWSER || 'msedge' })
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 } })
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    let status = 200, emptyTrades = false, submitted
    await page.route('**/api/runs?*', route => route.fulfill({ json: [] }))
    await page.route('**/api/backtests', async route => {
      submitted = route.request().postDataJSON()
      await new Promise(resolve => setTimeout(resolve, 150))
      if (status !== 200) return route.fulfill({ status, json: { detail: 'No price data was returned for this symbol.' } })
      const cash = submitted.initial_cash
      await route.fulfill({ json: {
        summary: { 'Total Return': .16, 'Benchmark Return': .08, 'Sharpe Ratio': null, 'Max Drawdown': -.05, 'Annualized Return': .12, 'Time in Market': .65, 'Annualized Volatility': .1, 'Number of Market Entries': 2, 'Sortino Ratio': 1.4 },
        equity: Array.from({ length: 40 }, (_, i) => ({ date: new Date(Date.UTC(2025, 0, i + 1)).toISOString().slice(0, 10), strategy: cash * (1 + i * .004 + Math.sin(i / 4) * .03), benchmark: cash * (1 + i * .002) })),
        trades: emptyTrades ? [] : [
          { entry_date: '2025-01-02', exit_date: '2025-01-09', entry_price: 100, exit_price: 105, holding_period: 5, net_return: .049 },
          { entry_date: '2025-01-12', exit_date: '2025-01-20', entry_price: 105, exit_price: 100, holding_period: 6, net_return: -.049 }
        ]
      } })
    })
    await page.goto(process.env.BACKTEST_URL || 'http://127.0.0.1:5175')
    await page.getByRole('heading', { name: 'Start with a question.' }).waitFor()
    await page.setViewportSize({ width: 1280, height: 720 })
    if (process.env.BACKTEST_SCREENSHOT) await page.screenshot({ path: process.env.BACKTEST_SCREENSHOT.replace('.png', '-start.png'), fullPage: true })
    await page.getByRole('button', { name: /Saved runs Open a previous result/ }).click()
    await page.getByText('No saved runs yet.').waitFor()
    await page.getByRole('tab', { name: 'Backtest', exact: true }).click()
    await page.getByRole('button', { name: /Journal Read or write an idea/ }).click()
    await page.getByRole('heading', { name: 'Journal', exact: true }).waitFor()
    await page.getByRole('tab', { name: 'Backtest', exact: true }).click()

    await page.getByRole('tab', { name: 'Journal', exact: true }).click()
    await page.getByRole('button', { name: 'Write your first idea' }).click()
    await page.getByLabel('Title', { exact: true }).fill('Momentum hypothesis')
    await page.getByLabel('Notes', { exact: true }).fill('Compare short and long lookback windows.')
    await page.getByRole('button', { name: 'Save & close' }).click()
    assert.equal(await page.getByLabel('Notes', { exact: true }).count(), 0)
    await page.reload()
    await page.getByRole('tab', { name: 'Journal', exact: true }).click()
    await page.getByRole('button', { name: /Momentum hypothesis/ }).click()
    assert.equal(await page.getByLabel('Title', { exact: true }).inputValue(), 'Momentum hypothesis')
    assert.equal(await page.getByLabel('Notes', { exact: true }).inputValue(), 'Compare short and long lookback windows.')
    await page.getByRole('button', { name: 'New idea' }).click()
    await page.getByLabel('Title', { exact: true }).fill('Second idea')
    await page.getByRole('button', { name: /Momentum hypothesis/ }).click()
    assert.equal(await page.getByLabel('Notes', { exact: true }).inputValue(), 'Compare short and long lookback windows.')
    await page.getByRole('tab', { name: 'Backtest', exact: true }).click()
    await page.mouse.move(5, 5)
    const pencilBounds = await page.getByRole('button', { name: 'Edit parameters', exact: true }).boundingBox()
    const journalBounds = await page.getByRole('tab', { name: 'Journal', exact: true }).boundingBox()
    await page.getByRole('button', { name: /Edit parameters/ }).click()
    const closeBounds = await page.getByRole('button', { name: 'Close parameters', exact: true }).boundingBox()
    const quickBounds = await page.getByRole('button', { name: 'Quick journal', exact: true }).boundingBox()
    assert.ok(Math.abs(pencilBounds.x - closeBounds.x) < 1 && Math.abs(pencilBounds.y - closeBounds.y) < 1, 'Pencil stays anchored')
    assert.ok(Math.abs(journalBounds.x - quickBounds.x) < 1 && Math.abs(journalBounds.y - quickBounds.y) < 1, 'Journal stays anchored')

    await page.waitForTimeout(240)
    const parameterBounds = await page.locator('.settings-panel').boundingBox()
    await page.getByRole('button', { name: 'Quick journal', exact: true }).click()
    await page.waitForTimeout(240)
    assert.deepEqual(await page.locator('.settings-panel').boundingBox(), parameterBounds)
    assert.equal(await page.getByText('Adjust your inputs. Keep your place.', { exact: true }).count(), 0)
    await page.getByLabel('Idea', { exact: true }).selectOption({ label: 'Momentum hypothesis' })
    await page.getByLabel('Quick journal reference').getByText('Compare short and long lookback windows.').waitFor()
    await page.getByRole('button', { name: 'Close parameters', exact: true }).click()
    await page.locator('dialog').waitFor({ state: 'hidden' })
    assert.equal(await page.locator('dialog').evaluate(el => el.getAnimations({ subtree: true }).length), 0)
    await page.getByRole('button', { name: 'Edit parameters', exact: true }).click()
    assert.equal(await page.getByLabel('Quick journal reference').count(), 0)
    for (const width of [1366, 1024]) {
      await page.setViewportSize({ width, height: 768 })
      for (const strategy of ['moving_average', 'momentum', 'mean_reversion']) {
        await page.getByRole('combobox', { name: /^Strategy/ }).selectOption(strategy)
        await page.evaluate(() => window.scrollTo(0, 0))
        const bounds = await page.locator('.settings-panel').boundingBox()
        assert.ok(bounds.y + bounds.height < 768, `Complete ${strategy} setup fits at ${width}×768`)
      }
    }
    if (process.env.BACKTEST_SCREENSHOT) await page.screenshot({ path: process.env.BACKTEST_SCREENSHOT.replace('.png', '-editor.png'), fullPage: true })
    await page.getByRole('combobox', { name: /^Strategy/ }).selectOption('moving_average')
    await page.getByLabel('Symbol', { exact: true }).fill('MSFT')
    await page.getByRole('button', { name: 'Close parameters' }).click()
    await page.getByRole('tab', { name: 'Saved runs', exact: true }).click()
    await page.getByText('No saved runs yet.').waitFor()
    await page.locator('dialog').waitFor({ state: 'hidden' })
    assert.equal(await page.locator('.settings-panel').isVisible(), false)
    await page.getByRole('tab', { name: 'Backtest', exact: true }).click()
    await page.getByRole('button', { name: /Edit parameters/ }).click()
    assert.equal(await page.getByLabel('Symbol', { exact: true }).inputValue(), 'MSFT')
    await page.getByLabel('Symbol', { exact: true }).fill('AAPL')
    await page.setViewportSize({ width: 1440, height: 900 })
    const run = page.getByRole('button', { name: 'Run backtest' })
    await run.click()
    await page.getByRole('heading', { name: /AAPL/ }).waitFor()
    assert.equal(submitted.strategy.name, 'moving_average')
    assert.equal(submitted.initial_cash, 10000)
    await page.getByRole('img', { name: /equity chart/ }).waitFor()
    await page.locator('dialog').waitFor({ state: 'hidden' })
    const scrubber = page.getByRole('slider', { name: 'Inspect chart observation' })
    await page.mouse.move(5, 5)
    await page.waitForTimeout(300)
    assert.equal(await scrubber.evaluate(el => getComputedStyle(el).opacity), '0')
    const beforeHover = await page.locator('.chart-container').boundingBox()
    await page.getByRole('img', { name: /equity chart/ }).hover()
    await page.waitForTimeout(300)
    assert.equal(await scrubber.evaluate(el => getComputedStyle(el).opacity), '1')
    assert.deepEqual(await page.locator('.chart-container').boundingBox(), beforeHover)
    await page.mouse.move(5, 5)
    await page.waitForTimeout(300)
    assert.equal(await scrubber.evaluate(el => getComputedStyle(el).opacity), '0')
    await page.keyboard.press('Tab')
    await scrubber.focus()
    await page.keyboard.press('ArrowLeft')
    await page.waitForTimeout(300)
    assert.equal(await scrubber.evaluate(el => getComputedStyle(el).opacity), '1')
    for (const index of [0, 19, 39]) {
      await scrubber.fill(String(index))
      const alignment = await page.evaluate(() => {
        const input = document.querySelector('.observation-slider')
        const rect = input.getBoundingClientRect()
        const thumbWidth = 11
        const thumbX = rect.left + thumbWidth / 2 + Number(input.value) / Number(input.max) * (rect.width - thumbWidth)
        const cursor = document.querySelector('.cursor-line').getBoundingClientRect()
        return Math.abs(thumbX - cursor.left)
      })
      assert.ok(alignment < 1, 'Scrubber thumb aligns with chart cursor')
    }
    await scrubber.blur()
    await page.locator('dialog').waitFor({ state: 'hidden' })
    for (const size of [{ width: 1366, height: 768 }, { width: 1024, height: 768 }, { width: 1280, height: 720 }]) {
      await page.setViewportSize(size)
      await page.waitForTimeout(100)
      const chart = await page.locator('.chart-panel').boundingBox()
      const footnote = await page.locator('.chart-panel .footnote').boundingBox()
      assert.ok(chart.y + chart.height <= size.height, 'Chart fits viewport')
      assert.ok(footnote.y + footnote.height <= size.height, 'Chart controls and notes fit viewport')
      assert.equal(await page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight), true)
    }
    await page.getByRole('tab', { name: 'Run details', exact: true }).click()
    await page.getByText('Run settings', { exact: false }).click()
    assert.match(await page.locator('.settings-summary').innerText(), /252/)
    await page.locator('.run-details summary').click()
    await page.getByRole('tab', { name: 'Performance overview' }).click()
    await page.getByRole('tab', { name: 'Performance overview' }).focus()
    await page.keyboard.press('ArrowRight')
    assert.equal(await page.getByRole('tab', { name: /Trade ledger/ }).getAttribute('aria-selected'), 'true')
    await page.keyboard.press('Home')
    assert.equal(await page.getByRole('tab', { name: 'Performance overview' }).getAttribute('aria-selected'), 'true')
    await page.getByRole('button', { name: 'Drawdown', exact: true }).click()
    await page.getByRole('img', { name: /drawdown chart/ }).waitFor()
    await page.getByRole('slider').fill('5')
    await page.getByLabel('Chart start date').fill('2025-01-10')
    await page.getByRole('button', { name: 'Full range' }).click()
    if (process.env.BACKTEST_SCREENSHOT) await page.screenshot({ path: process.env.BACKTEST_SCREENSHOT, fullPage: true })
    await page.getByRole('tab', { name: /Trade ledger/ }).click()
    assert.equal(await page.locator('tbody tr').count(), 2)
    await page.getByRole('button', { name: /Net return/ }).click()
    assert.match(await page.locator('tbody tr').first().innerText(), /-4.90%/)
    await page.getByLabel(/^Show/).selectOption('wins')
    assert.equal(await page.locator('tbody tr').count(), 1)
    const downloadEvent = page.waitForEvent('download')
    await page.getByRole('button', { name: /Export CSV/ }).click()
    const download = await downloadEvent
    assert.equal(download.suggestedFilename(), 'AAPL-trades.csv')
    await page.getByRole('button', { name: /Edit parameters/ }).click()
    await page.getByLabel('Symbol', { exact: true }).fill('MSFT')
    await page.getByText('Settings changed.', { exact: false }).waitFor()
    await page.getByRole('combobox', { name: /^Strategy/ }).selectOption('mean_reversion')
    await page.getByLabel('Entry distance %').fill('6')
    await run.click()
    await page.getByRole('heading', { name: /MSFT/ }).waitFor()
    assert.equal(submitted.strategy.entry_distance, .06)
    await page.getByRole('button', { name: /Edit parameters/ }).click()
    await page.getByRole('combobox', { name: /^Strategy/ }).selectOption('momentum')
    emptyTrades = true
    await run.click()
    await page.getByText('No completed trades.', { exact: false }).waitFor()
    assert.equal(submitted.strategy.name, 'momentum')
    status = 502
    await page.getByRole('button', { name: /Edit parameters/ }).click()
    await run.click()
    await page.getByRole('alert').filter({ hasText: 'No price data' }).waitFor()
    await page.keyboard.press('Escape')
    await page.setViewportSize({ width: 390, height: 844 })
    await page.getByRole('tab', { name: 'Performance overview' }).click()
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true)
    if (process.env.BACKTEST_SCREENSHOT) await page.screenshot({ path: process.env.BACKTEST_SCREENSHOT.replace('.png', '-mobile.png'), fullPage: true })
    assert.deepEqual(errors, [])
    console.log('PASS: three strategies, request values, charts, date range, slider, null metric, sorting, filter, export, empty ledger, failed run, stale notice, mobile layout; no browser runtime errors.')
  } finally { await browser.close() }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
